// <auto-generated />
namespace Invoices.Dataa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InvoicesData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoicesData));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071727351_Invoices.Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
